# Creamos este docker compose prod ya que en el docker compose por defecto hacemos bind volume y esto podria ser un problema en produccion

version: '3'

services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: diegoegj/nest-teslo-shop-app:1.0.0
    container_name: nest-teslo-shop-app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false
