version: '3'

services:
  app:
    build:
      context: . # the '.' means the current directory
      target: dev # target stage to build, you can also especify it in the .env file
      dockerfile: Dockerfile
    # command: yarn start:dev # se puede usar de esta manera si no hay un CMD en el Dockerfile.
    volumes:
      - .:/app
      - /app/node_modules # this is to prevent the node_modules from inside the container to be overwritten by the local node_modules, it is called volume shadowing
    container_name: nest-teslo-shop-app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false
